import { randomUUID } from "node:crypto";
import prisma, { withTenantTx } from "../lib/prisma";

export interface ChunkInsert {
    chunkIndex: number;
    content: string;
    characterStart: number;
    characterEnd: number;
    tokenEstimate: number;
    embedding: number[];
}

/**
 * Storage for document_chunks. The embedding column is pgvector
 * (Unsupported in Prisma), so inserts use raw SQL with a `$n::vector` cast —
 * same pattern as MemoryEmbeddingRepository.
 */
export class DocumentChunkRepository {
    deleteByFile(fileId: string) {
        return prisma.documentChunk.deleteMany({ where: { fileId } });
    }

    countByFile(fileId: string) {
        return prisma.documentChunk.count({ where: { fileId } });
    }

    /**
     * All chunks for a file in reading order. Used by the Requirement Extractor
     * to reconstruct a file's ingested text as the extraction source (keeping
     * provenance to the originating ProjectFile).
     */
    findByFileOrdered(fileId: string) {
        return prisma.documentChunk.findMany({
            where: { fileId },
            orderBy: { chunkIndex: "asc" },
            select: { content: true },
        });
    }

    /**
     * Atomically replace all chunks for a file (delete existing + insert new)
     * so a re-index is all-or-nothing. Embeddings are generated by the caller
     * beforehand, keeping this transaction short (no inference inside it).
     */
    async replaceChunks(fileId: string, projectId: string, chunks: ChunkInsert[]) {
        await withTenantTx(async (tx) => {
            await tx.documentChunk.deleteMany({ where: { fileId } });

            for (const chunk of chunks) {
                const vector = `[${chunk.embedding.join(",")}]`;

                await tx.$executeRawUnsafe(
                    `
                    INSERT INTO "document_chunks"
                    ("id","fileId","projectId","chunkIndex","content","characterStart","characterEnd","tokenEstimate","embedding","createdAt")
                    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::vector,NOW())
                    `,
                    randomUUID(),
                    fileId,
                    projectId,
                    chunk.chunkIndex,
                    chunk.content,
                    chunk.characterStart,
                    chunk.characterEnd,
                    chunk.tokenEstimate,
                    vector
                );
            }
        });
    }
}

export default new DocumentChunkRepository();
