import { randomUUID } from "node:crypto";
import { SearchableSourceType } from "@prisma/client";

import prisma, { withTenantTx } from "../lib/prisma";

export interface SearchableChunkInsert {
  chunkIndex: number;
  content: string;
  metadata: Record<string, unknown> | null;
  embedding: number[];
}

/**
 * Storage for searchable_chunks (Unified Retrieval phase — P1). The `embedding`
 * column is pgvector (Unsupported in Prisma), so writes use raw SQL with a
 * `$n::vector` cast — same pattern as DocumentChunkRepository / MemoryEmbedding.
 *
 * Writes go through withTenantTx so the tenant GUC is applied on the same
 * connection: the searchable_chunks RLS policy is strict (via projectId), so an
 * INSERT must run under the owning tenant's context or its WITH CHECK rejects
 * the row. At runtime the request supplies that context; the backfill supplies
 * it via runWithTenantContext.
 *
 * This repository only WRITES. Retrieval/search over this table is P2 and is not
 * implemented here.
 */
export class SearchableChunkRepository {
  /**
   * Atomically replace all chunks for one source (delete existing + insert new),
   * so a re-index is all-or-nothing. Embeddings are generated by the caller
   * beforehand, keeping the transaction short (no inference inside it).
   */
  async replaceBySource(
    projectId: string,
    sourceType: SearchableSourceType,
    sourceId: string,
    chunks: SearchableChunkInsert[],
  ): Promise<void> {
    await withTenantTx(async (tx) => {
      await tx.$executeRawUnsafe(
        `DELETE FROM "searchable_chunks" WHERE "sourceType" = $1::"SearchableSourceType" AND "sourceId" = $2`,
        sourceType,
        sourceId,
      );

      for (const chunk of chunks) {
        const vector = `[${chunk.embedding.join(",")}]`;

        await tx.$executeRawUnsafe(
          `
          INSERT INTO "searchable_chunks"
          ("id","projectId","sourceType","sourceId","chunkIndex","content","metadata","embedding","createdAt","updatedAt")
          VALUES ($1,$2,$3::"SearchableSourceType",$4,$5,$6,$7::jsonb,$8::vector,NOW(),NOW())
          `,
          randomUUID(),
          projectId,
          sourceType,
          sourceId,
          chunk.chunkIndex,
          chunk.content,
          chunk.metadata ? JSON.stringify(chunk.metadata) : null,
          vector,
        );
      }
    });
  }

  /**
   * Project-scoped vector similarity search over the unified index (P2). Mirrors
   * the legacy per-store searches (raw SQL, cosine `<=>`), but returns every
   * content type in one query — backed by the HNSW index. Project-scoped in SQL
   * AND tenant-scoped by RLS (the ambient context), i.e. defence in depth.
   *
   * `sourceTypes` (P3) optionally restricts the search to specific source kinds
   * — e.g. requirement extraction retrieves only MEMORY + DOCUMENT so it never
   * feeds on existing requirements. Omitted → all types.
   */
  async search(
    projectId: string,
    embedding: number[],
    limit: number,
    sourceTypes?: SearchableSourceType[],
  ) {
    const vector = `[${embedding.join(",")}]`;
    const params: unknown[] = [vector, projectId, limit];

    let typeFilter = "";
    if (sourceTypes && sourceTypes.length > 0) {
      params.push(sourceTypes);
      typeFilter = `AND "sourceType"::text = ANY($4)`;
    }

    return prisma.$queryRawUnsafe(
      `
      SELECT
        "id"          AS "chunkId",
        "sourceType",
        "sourceId",
        "chunkIndex",
        "content",
        "metadata",
        "embedding" <=> $1::vector AS distance
      FROM "searchable_chunks"
      WHERE "projectId" = $2
      ${typeFilter}
      ORDER BY "embedding" <=> $1::vector
      LIMIT $3
      `,
      ...params,
    );
  }

  /**
   * Lexical half of hybrid retrieval. The caller supplies a sanitized
   * PostgreSQL tsquery (meaningful terms joined with `|`) so natural-language
   * questions can match exact names, identifiers, and uncommon terminology
   * that semantic embeddings sometimes underweight.
   */
  async searchKeyword(
    projectId: string,
    embedding: number[],
    tsQuery: string,
    phrase: string,
    limit: number,
    sourceTypes?: SearchableSourceType[],
  ) {
    const vector = `[${embedding.join(",")}]`;
    const params: unknown[] = [vector, projectId, tsQuery, phrase, limit];

    let typeFilter = "";
    if (sourceTypes && sourceTypes.length > 0) {
      params.push(sourceTypes);
      typeFilter = `AND "sourceType"::text = ANY($6)`;
    }

    return prisma.$queryRawUnsafe(
      `
      SELECT
        "id" AS "chunkId",
        "sourceType",
        "sourceId",
        "chunkIndex",
        "content",
        "metadata",
        "embedding" <=> $1::vector AS distance,
        ts_rank_cd(
          to_tsvector('english', "content"),
          to_tsquery('english', $3)
        ) AS "keywordRank",
        CASE WHEN $4 <> '' AND "content" ILIKE '%' || $4 || '%' THEN 1 ELSE 0 END AS "phraseMatch"
      FROM "searchable_chunks"
      WHERE "projectId" = $2
        AND (
          to_tsvector('english', "content") @@ to_tsquery('english', $3)
          OR ($4 <> '' AND "content" ILIKE '%' || $4 || '%')
        )
      ${typeFilter}
      ORDER BY "phraseMatch" DESC, "keywordRank" DESC, distance ASC
      LIMIT $5
      `,
      ...params,
    );
  }

  /** Remove all chunks for a source (used when the origin row is deleted/emptied). */
  async deleteBySource(
    sourceType: SearchableSourceType,
    sourceId: string,
  ): Promise<void> {
    // A single raw op — the $allOperations extension applies the tenant GUC
    // automatically, so the RLS USING clause scopes the delete to this tenant.
    await prisma.$executeRawUnsafe(
      `DELETE FROM "searchable_chunks" WHERE "sourceType" = $1::"SearchableSourceType" AND "sourceId" = $2`,
      sourceType,
      sourceId,
    );
  }

  /**
   * Remove every chunk for a project — used by the reindex backfill to do a
   * clean rebuild, so rows from now-excluded or deleted sources leave no residue.
   * Project-scoped in SQL AND tenant-scoped by RLS.
   */
  async deleteByProject(projectId: string): Promise<void> {
    await prisma.$executeRawUnsafe(
      `DELETE FROM "searchable_chunks" WHERE "projectId" = $1`,
      projectId,
    );
  }
}

export default new SearchableChunkRepository();
